2021-05-05 22:20:46,556 INFO    MainThread:13944 [wandb_setup.py:_flush():69] setting env: {'project': 'exercise_10', 'run_group': 'dev'}
2021-05-05 22:20:46,556 INFO    MainThread:13944 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-05 22:20:46,557 INFO    MainThread:13944 [wandb_init.py:_log_setup():334] Logging user logs to /home/giacomov/udacity/repo/nd0821-c2-build-model-workflow/lesson-4-training-validation-experiment-tracking/exercises/exercise_10/solution/random_forest/wandb/run-20210505_222046-1xk1czpv/logs/debug.log
2021-05-05 22:20:46,557 INFO    MainThread:13944 [wandb_init.py:_log_setup():335] Logging internal logs to /home/giacomov/udacity/repo/nd0821-c2-build-model-workflow/lesson-4-training-validation-experiment-tracking/exercises/exercise_10/solution/random_forest/wandb/run-20210505_222046-1xk1czpv/logs/debug-internal.log
2021-05-05 22:20:46,558 INFO    MainThread:13944 [wandb_init.py:init():367] calling init triggers
2021-05-05 22:20:46,558 INFO    MainThread:13944 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-05-05 22:20:46,558 INFO    MainThread:13944 [wandb_init.py:init():416] starting backend
2021-05-05 22:20:46,559 INFO    MainThread:13944 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-05 22:20:46,575 INFO    MainThread:13944 [backend.py:ensure_launched():123] starting backend process...
2021-05-05 22:20:46,579 INFO    MainThread:13944 [backend.py:ensure_launched():127] started backend process with pid: 13969
2021-05-05 22:20:46,580 INFO    MainThread:13944 [wandb_init.py:init():421] backend started and connected
2021-05-05 22:20:46,581 INFO    MainThread:13944 [wandb_init.py:init():461] updated telemetry
2021-05-05 22:20:46,581 INFO    MainThread:13944 [wandb_init.py:init():480] communicating current version
2021-05-05 22:20:47,065 INFO    MainThread:13944 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.29 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-05 22:20:47,066 INFO    MainThread:13944 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-05-05 22:20:47,248 INFO    MainThread:13944 [wandb_init.py:init():518] starting run threads in backend
2021-05-05 22:20:47,297 INFO    MainThread:13944 [wandb_run.py:_console_start():1476] atexit reg
2021-05-05 22:20:47,298 INFO    MainThread:13944 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.REDIRECT
2021-05-05 22:20:47,298 INFO    MainThread:13944 [wandb_run.py:_redirect():1344] Redirecting console.
2021-05-05 22:20:47,298 INFO    MainThread:13944 [redirect.py:install():213] install start
2021-05-05 22:20:47,298 INFO    MainThread:13944 [redirect.py:install():228] install stop
2021-05-05 22:20:47,298 INFO    MainThread:13944 [redirect.py:install():213] install start
2021-05-05 22:20:47,299 INFO    MainThread:13944 [redirect.py:install():228] install stop
2021-05-05 22:20:47,299 INFO    MainThread:13944 [wandb_run.py:_redirect():1390] Redirects installed.
2021-05-05 22:20:47,299 INFO    MainThread:13944 [wandb_init.py:init():542] run started, returning control to user process
2021-05-05 22:20:48,086 INFO    MainThread:13944 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 1
2021-05-05 22:20:48,086 INFO    MainThread:13944 [wandb_run.py:_restore():1418] restore
2021-05-05 22:20:48,086 INFO    MainThread:13944 [redirect.py:uninstall():232] uninstall start
2021-05-05 22:20:48,087 INFO    MainThread:13944 [redirect.py:_stop():287] _stop: stdout
2021-05-05 22:20:48,087 INFO    stdout    :13944 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-05-05 22:20:48,087 INFO    stdout    :13944 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-05-05 22:20:48,087 INFO    MainThread:13944 [redirect.py:_stop():293] _stop closed: stdout
2021-05-05 22:20:48,087 INFO    MainThread:13944 [redirect.py:_stop():299] _stop joined: stdout
2021-05-05 22:20:48,087 INFO    MainThread:13944 [redirect.py:_stop():301] _stop rd closed: stdout
2021-05-05 22:20:48,087 INFO    MainThread:13944 [redirect.py:uninstall():236] uninstall done
2021-05-05 22:20:48,087 INFO    MainThread:13944 [redirect.py:uninstall():232] uninstall start
2021-05-05 22:20:48,088 INFO    MainThread:13944 [redirect.py:_stop():287] _stop: stderr
2021-05-05 22:20:48,088 INFO    MainThread:13944 [redirect.py:_stop():293] _stop closed: stderr
2021-05-05 22:20:48,088 INFO    stderr    :13944 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-05-05 22:20:48,088 INFO    stderr    :13944 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-05-05 22:20:48,088 INFO    MainThread:13944 [redirect.py:_stop():299] _stop joined: stderr
2021-05-05 22:20:48,088 INFO    MainThread:13944 [redirect.py:_stop():301] _stop rd closed: stderr
2021-05-05 22:20:48,088 INFO    MainThread:13944 [redirect.py:uninstall():236] uninstall done
2021-05-05 22:20:48,221 INFO    MainThread:13944 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1213
  total_bytes: 1213
}

2021-05-05 22:20:50,227 INFO    MainThread:13944 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2591
  total_bytes: 2591
}

2021-05-05 22:20:51,279 INFO    MainThread:13944 [wandb_run.py:_show_files():1790] logging synced files
